-- 2. Grant access to your API schema (e.g., 'public')
GRANT USAGE ON SCHEMA public TO anon;

DROP TABLE IF EXISTS tagraccolti CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS partecipazioni CASCADE;
DROP TABLE IF EXISTS partite CASCADE;
DROP TABLE IF EXISTS notifiche CASCADE;
DROP TABLE IF EXISTS utenti CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;

-- Creazione tabelle
CREATE TABLE utenti (
    ute_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    ute_username text NOT NULL,
    ute_immagine text NOT NULL,
    unique(ute_username)
);
GRANT SELECT ON public.utenti TO anon;

CREATE TABLE partite (
    par_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    par_nome text NULL,
    par_organizzatore UUID NOT NULL,
    par_latitudine FLOAT NOT NULL,
    par_longitudine FLOAT NOT NULL,
    par_timestamp_inizio TIMESTAMPTZ NOT NULL,
    par_timestamp_fine TIMESTAMPTZ NOT NULL,
    par_descrizione text NULL,
    par_codice text NOT NULL,
    par_privato boolean NOT NULL DEFAULT (false),
    FOREIGN KEY (par_organizzatore) REFERENCES utenti(ute_id)
);
GRANT SELECT ON public.partite TO anon;

CREATE TABLE partecipazioni (
    prt_partita INT NOT NULL,
    prt_utente UUID NOT NULL,
    FOREIGN KEY (prt_partita) REFERENCES partite(par_id),
    FOREIGN KEY (prt_utente) REFERENCES utenti(ute_id),
    PRIMARY KEY (prt_partita, prt_utente)
);

CREATE TABLE tags (
    tag_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tag_posizione INT NOT NULL,
    tag_partita INT NOT NULL,
    tag_latitudine FLOAT NOT NULL,
    tag_longitudine FLOAT NOT NULL,
    tag_indizio text NULL,
    tag_immagine text NULL,
    FOREIGN KEY (tag_partita) REFERENCES partite(par_id)
);

CREATE TABLE tagraccolti (
    tgr_tag UUID NOT NULL,
    tgr_utente UUID NOT NULL,
    FOREIGN KEY (tgr_tag) REFERENCES tags(tag_id),
    FOREIGN KEY (tgr_utente) REFERENCES utenti(ute_id),
    PRIMARY KEY (tgr_tag, tgr_utente)
);

CREATE TABLE notifiche (
    not_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    not_utente UUID NOT NULL,
    not_data timestamp default now(),
    not_messaggio text,
    not_letto boolean default false,
    FOREIGN KEY (not_utente) REFERENCES utenti(ute_id)
);

-- Funzione che copia l'utente da auth.users a public.utenti
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.utenti (ute_id, ute_username, ute_immagine)
  VALUES (
    new.id, 
    -- Usa l'username dai metadati, ma se è NULL usa l'email dell'utente
    COALESCE(new.raw_user_meta_data->>'username', new.email), 
    'default.png'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger che attiva la funzione al momento del signUp
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ==========================================
-- INSERIMENTO DATI
-- ==========================================

-- 1. Inserimento Utenti
INSERT INTO utenti (ute_id, ute_username, ute_immagine) VALUES 
('115133f6-4760-4214-bcb2-51d33f281211', 'mattia.cavina2@studio.unibo.it', 'default.png'),
('970be8b4-7771-4e8a-90af-d4336b9eecf0', 'matteo.grandini@studio.unibo.it', 'default.png'),
('a6f03999-fcd7-4fa1-976c-6c1187a1c109', 'giuliabianchi@example.it', 'default.png'),
('7e29a1ec-ece2-4076-80b4-4284059e5a2e', 'annaneri@example.it', 'default.png');

-- 2. Inserimento Partite
INSERT INTO partite (par_nome, par_organizzatore, par_latitudine, par_longitudine, par_timestamp_inizio, par_timestamp_fine, par_descrizione, par_codice) VALUES 
('PARTITA1','115133f6-4760-4214-bcb2-51d33f281211', 45.4642, 9.1900,  NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', 'Caccia al tesoro Milano' ,'HASH_1_XDFS'),
('PARTITA2','115133f6-4760-4214-bcb2-51d33f281211', 41.9028, 12.4964, NOW() - INTERVAL '1 day', NOW(), 'Caccia al tesoro Roma' ,'HASH_2_XDFS'),
('PARTITA3','970be8b4-7771-4e8a-90af-d4336b9eecf0', 43.7696, 11.2558, NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days', 'Caccia al tesoro Firenze' ,'HASH_3_XDFS'),
('PARTITA4','a6f03999-fcd7-4fa1-976c-6c1187a1c109', 45.4384, 10.9916, NOW() - INTERVAL '1 day', NOW(), 'Caccia al tesoro Verona' ,'HASH_4_XDFS'),
('PARTITA5','7e29a1ec-ece2-4076-80b4-4284059e5a2e', 40.8518, 14.2681, NOW(), NOW() + INTERVAL '1 day', 'Caccia al tesoro Napoli' ,'HASH_5_XDFS'); 

-- 3. Creare delle partecipazioni (Sostituiti i numeri utente con gli UUID)
INSERT INTO partecipazioni (prt_partita, prt_utente) VALUES
(1, '970be8b4-7771-4e8a-90af-d4336b9eecf0'),
(1, 'a6f03999-fcd7-4fa1-976c-6c1187a1c109'),
(1, '7e29a1ec-ece2-4076-80b4-4284059e5a2e'),
(2, '115133f6-4760-4214-bcb2-51d33f281211'),
(2, 'a6f03999-fcd7-4fa1-976c-6c1187a1c109'),
(3, '7e29a1ec-ece2-4076-80b4-4284059e5a2e'),
(3, '115133f6-4760-4214-bcb2-51d33f281211');

-- 4. Aggiunta tag
WITH Nums AS (
    SELECT generate_series(1, 5) AS n
)
INSERT INTO tags (
    tag_posizione,
    tag_partita,
    tag_hash,
    tag_latitudine,
    tag_longitudine,
    tag_indizio,
    tag_immagine
)
SELECT 
    n.n AS tag_posizione,
    p.par_id AS tag_partita,
    CONCAT('HASH_', p.par_id, '_', n.n, '_', LEFT(CAST(gen_random_uuid() AS text), 8)) AS tag_hash,
    p.par_latitudine + (random() * 0.02 - 0.01) AS tag_latitudine,
    p.par_longitudine + (random() * 0.02 - 0.01) AS tag_longitudine,
    CONCAT('Tag n.', n.n, ' - Partita ', p.par_id) AS tag_descrizione,
    'upload/default.jpg' AS tag_immagine
FROM 
    partite p
CROSS JOIN 
    Nums n;

-- 5. Inserimento Notifiche
INSERT INTO notifiche (not_utente,not_messaggio) VALUES 
('115133f6-4760-4214-bcb2-51d33f281211','PROVA1'),
('115133f6-4760-4214-bcb2-51d33f281211','PROVA2'),
('115133f6-4760-4214-bcb2-51d33f281211','PROVA3'),
('970be8b4-7771-4e8a-90af-d4336b9eecf0','PROVA1'),
('970be8b4-7771-4e8a-90af-d4336b9eecf0','PROVA2'),
('a6f03999-fcd7-4fa1-976c-6c1187a1c109','PROVA3');

-- ==========================================
-- ROW LEVEL SECURITY (RLS) & POLICIES
-- ==========================================

-- Abilita RLS su tutte le tabelle
ALTER TABLE notifiche ENABLE ROW LEVEL SECURITY;
ALTER TABLE utenti ENABLE ROW LEVEL SECURITY;
ALTER TABLE partite ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE partecipazioni ENABLE ROW LEVEL SECURITY;
ALTER TABLE tagraccolti ENABLE ROW LEVEL SECURITY;

-- Creazione delle policy
CREATE POLICY "Permetti tutto agli utenti autenticati su notifiche" ON public.notifiche FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permetti tutto agli utenti autenticati su utenti" ON public.utenti FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permetti tutto agli utenti autenticati su partite" ON public.partite FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permetti tutto agli utenti autenticati su tags" ON public.tags FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permetti tutto agli utenti autenticati su partecipazioni" ON public.partecipazioni FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permetti tutto agli utenti autenticati su tagraccolti" ON public.tagraccolti FOR ALL TO authenticated USING (true) WITH CHECK (true);