-- Pulizia iniziale: elimina le tabelle se esistono già (utile per resettare l'ambiente)
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS partecipazione CASCADE;
DROP TABLE IF EXISTS partita CASCADE;
DROP TABLE IF EXISTS utente CASCADE;
DROP TABLE IF EXISTS notifiche CASCADE;

-- Creazione tabelle
CREATE TABLE utente (
    ute_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ute_username VARCHAR(50) NOT NULL,
    ute_password VARCHAR(50) NOT NULL,
    ute_immagine VARCHAR(100) NOT NULL
);

CREATE TABLE partita (
    par_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    par_nome VARCHAR(50) NULL,
    par_organizzatore INT NOT NULL,
    par_latitudine FLOAT NOT NULL,
    par_longitudine FLOAT NOT NULL,
    par_data TIMESTAMP NOT NULL, -- Supabase consiglia TIMESTAMPTZ, ma TIMESTAMP va bene per emulare DATETIME
    par_descrizione VARCHAR(100) NULL,
    par_codiice VARCHAR(20),
    FOREIGN KEY (par_organizzatore) REFERENCES utente(ute_id)
);

CREATE TABLE partecipazione (
    prt_partita INT NOT NULL,
    prt_utente INT NOT NULL,
    FOREIGN KEY (prt_partita) REFERENCES partita(par_id),
    FOREIGN KEY (prt_utente) REFERENCES utente(ute_id),
    PRIMARY KEY (prt_partita, prt_utente)
);

CREATE TABLE tag (
    tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_posizione INT NOT NULL,
    tag_partita INT NOT NULL,
    tag_hash VARCHAR(50) NOT NULL,
    tag_latitudine FLOAT NOT NULL,
    tag_longitudine FLOAT NOT NULL,
    tag_descrizione VARCHAR(100) NOT NULL,
    tag_immagine VARCHAR(100) NOT NULL,
    FOREIGN KEY (tag_partita) REFERENCES partita(par_id)
);

CREATE TABLE NOTIFICHE (
    not_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    not_utente INT NOT NULL,
    not_data timestamp default now(),
    not_messaggio VARCHAR(150),
    not_letto boolean  default false,
    FOREIGN KEY (not_utente) REFERENCES utente(ute_id)
);

-- 1. Inserimento Utenti (Sintassi compatta con VALUES multipli)
INSERT INTO utente (ute_username, ute_password, ute_immagine) VALUES 
('mattia.cavina2@studio.unibo.it', 'pwd123', 'default.png'),
('matteo.grandini@studio.unibo.it', 'pwd123', 'default.png'),
('giuliabianchi@example.it', 'pwd123', 'default.png'),
('annaneri@example.it', 'pwd123', 'default.png');

-- 2. Inserimento Partite 
-- Sostituito GETDATE() con NOW() e DATEADD con gli INTERVAL di Postgres
INSERT INTO partita (par_organizzatore, par_latitudine, par_longitudine, par_data) VALUES 
(1, 45.4642, 9.1900,  NOW() - INTERVAL '2 days'), -- Milano
(1, 41.9028, 12.4964, NOW() - INTERVAL '1 day'),  -- Roma
(2, 43.7696, 11.2558, NOW() - INTERVAL '3 days'), -- Firenze
(3, 45.4384, 10.9916, NOW() - INTERVAL '1 day'),  -- Verona
(4, 40.8518, 14.2681, NOW());                     -- Napoli

-- 3. Creare delle partecipazioni 
INSERT INTO partecipazione (prt_partita, prt_utente) VALUES
(1, 2),
(1, 3),
(1, 4),
(2, 1),
(2, 3),
(3, 4),
(3, 1);

-- 4. Aggiunta tag
-- Sostituito il trucco della CTE manuale con generate_series() nativo di Postgres
WITH Nums AS (
    SELECT generate_series(1, 5) AS n
)
INSERT INTO tag (
    tag_posizione,
    tag_partita,
    tag_hash,
    tag_latitudine,
    tag_longitudine,
    tag_descrizione,
    tag_immagine
)
SELECT 
    n.n AS tag_posizione,
    p.par_id AS tag_partita,
    -- NEWID() diventa gen_random_uuid() in Postgres
    CONCAT('HASH_', p.par_id, '_', n.n, '_', LEFT(CAST(gen_random_uuid() AS VARCHAR(50)), 8)) AS tag_hash,
    -- CHECKSUM non esiste. Usiamo random() che genera un float tra 0.0 e 1.0.
    -- (random() * 0.02 - 0.01) restituisce esattamente un offset tra -0.01 e +0.01
    p.par_latitudine + (random() * 0.02 - 0.01) AS tag_latitudine,
    p.par_longitudine + (random() * 0.02 - 0.01) AS tag_longitudine,
    CONCAT('Tag n.', n.n, ' - Partita ', p.par_id) AS tag_descrizione,
    'upload/default.jpg' AS tag_immagine
FROM 
    partita p
CROSS JOIN 
    Nums n;

INSERT INTO NOTIFICHE (not_utente,not_messaggio) VALUES 
(1,'PROVA1'),
(1,'PROVA2'),
(1,'PROVA3'),
(2,'PROVA1'),
(2,'PROVA2'),
(3,'PROVA3');
